spring:
  application:
    name:user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hjc
    username: root
    password: 1776397883
  session:
    timeout: 86400
server:
  port: 8080


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false # 关闭驼峰转下划线
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-not-delete-value: 0     # 逻辑未删除值(默认为0)
      logic-delete-value: 1         # 逻辑已删除值(默认为1)

